# Numpy

Numpy is a library which provides support for large, homogenous, multi-dimensional arrays and matrices.


In [1]:
# importing numpy
import numpy as np

## Creating Arrays in Numpy

### Creating an array from a list

In [2]:
list1 = [10,20,30]
list1

[10, 20, 30]

In [3]:
arr1 = np.array(list1)
arr1  # Notice the differences in the output

array([10, 20, 30])

In [4]:
# We can check the type of arr1, we can see it is an ndarray 
# (or n-dimensional array)
# In this case we have only created a one dimensional array so far

type(arr1)

numpy.ndarray

### Using arange to create an array
The difference between array and arange is that array takes in a list and turns it into an array, whereas arange creates an array from a range of numbers

In [25]:
arr2 = np.arange(10,20, 1)  # (Start, Stop(non-inclusive), Step-size)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Multidimensional arrays
### Combining two lists - Two-dimensional arrays
When we combine arrays together, we can add dimensions. Combining two arrays will give us a two-dimensional array. This creates a matrix for us on which we can perform matrix operations.

In [8]:
# let's create a new list we can join onto the first list
list2 = [40,50,60]

# Now we will join the two lists together
list3 = [list1,list2]

# Create an array out of the joined lists
arr3 = np.array(list3)
arr3  # What do we notice about the shape?

array([[10, 20, 30],
       [40, 50, 60]])

In [12]:
# let's find the shape of our new array
# We have a two-dimensional array, with 2 elements in the first instance, and 3 in the second
arr3.shape

(2, 3)

### Three-dimensional arrays

In [14]:
arr3dim = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])

arr3dim  # What do we think the shape of this array will be?

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [16]:
arr3dim.shape

(2, 2, 3)

## Using Arrays and Scalars
As mentioned previously, numpy arrays (or ndarray) allow us to perform matrix operations.

In [20]:
# We can perform simple multiplication
# For example, what will this look like?
arr3dim * 3

array([[[ 3,  6,  9],
        [ 9, 12, 15]],

       [[15, 18, 21],
        [21, 24, 27]]])

In [19]:
# How is this different than trying to do:
list1 * 3
# This is where the numpy magic happens. Lists and arrays are treated differently. 

[10, 20, 30, 10, 20, 30, 10, 20, 30]

We can also multiply an array by another array, using a matrix operation

In [22]:
# Creating another array which has the same size as arr1
arr11 = np.array(list2)  

# What do we think will happen here?
# Individual numbers will be multiplied based on their positions
arr1 * arr11

array([ 400, 1000, 1800])

In [26]:
# What if we tried to multiply arrays of different shapes? Is it possible?
# The answer is - no
arr1 * arr2

ValueError: operands could not be broadcast together with shapes (3,) (10,) 

In [27]:
# But it is possible to multiply together arrays with different dimensions, but the same element size:
arr1 * arr3dim

array([[[ 10,  40,  90],
        [ 30,  80, 150]],

       [[ 50, 120, 210],
        [ 70, 160, 270]]])

## Lab

5-10 minutes.
Create ndarrays of the following sizes:
- One dimensional array with 12 elements (12,)
- Two dimensional array size (3, 4)
- Three dimensional array size (2, 5, 4)

Check the size of your ndarray to ensure it is correct

## Accessing values in ndarrays
Let's take arr3 as an example, which was a two-dimensional array

In [29]:
# How can we access the 60?
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [35]:
# We can use indexing
# Inxeding starts at 0, and will access each piece of the ndarray in order
arr3[1][2]

# we can also simply just do:
arr3[1,2]

60

In [31]:
# For example, if we wanted the bottom 'row' in our ndarray, we could do this:
arr3[1]

array([40, 50, 60])

In [36]:
# It's east to access each row, and specific values like this but what if we wanted just the last column?
# : means everything, so essentially we are selecting everything, and then just position 2 of the result
arr3[:,2]

array([30, 60])

## Statistical functions and arrays
We have a number of built in statistical functions we can use

In [37]:
# Finding the total sum of all values
arr3.sum()

210

In [38]:
# Finding the sum of values column-wise
arr3.sum(0)

array([50, 70, 90])

In [39]:
# Finding the sum of values row-wise
arr3.sum(1)

array([ 60, 150])

In [40]:
# Finding mean
arr3.mean()

35.0

In [41]:
# Finding Standard Deviation
arr3.std()

17.07825127659933

In [42]:
# Finding variance
arr3.var()

291.6666666666667

In [45]:
# Finding minimum value 
arr3.min()

10

In [46]:
# Finding maximum value
arr3.max()

60

## Iterating through ndarrays
The simplest way to get all values of an array in numpy is using a simple for loop.

In [48]:
# If we are using a one-dimensional array:
for x in arr1:
    print(x)

10
20
30


In [50]:
# If dealing with an n-dimensional array, we need to iterate through each dimension until we get the value
for dim in arr3:
    for num in dim:
        print(num)

10
20
30
40
50
60


In [51]:
# Alternatively - we can use nditer
# This can be used from very basic to very complex iterations
# It will be much neater than nested for loops
for x in np.nditer(arr3):
    print(x)

10
20
30
40
50
60


## Saving and loading in numpy

In [52]:
# To save an array as a file
np.save("new",arr3)

In [53]:
# Loading the file
np.load("new.npy")

array([[10, 20, 30],
       [40, 50, 60]])

In [54]:
# Saving as txt
np.savetxt("new.txt",arr3,delimiter=',')

In [55]:
# Loading a txt
np.loadtxt("new.txt",delimiter=',')

array([[10., 20., 30.],
       [40., 50., 60.]])